<?php
	
	namespace system\modules\filemanager\widget;
	
	use system\modules\filemanager\assets\FileSelectorAsset;
	use yii\widgets\InputWidget;
	
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: 12/30/2018
	 * Time: 4:05 AM
	 */
	class FileSelectorWidget extends InputWidget {
		public $multiple = false;
		
		
		public function run() {
			
			
			parent::run(); // TODO: Change the autogenerated stub
			FileSelectorAsset::register( $this->view );
			echo $this->render(
				'@system/modules/filemanager/widget/views/widget.php' ,
				[
					'id'        => $this->id ,
					'name'      => $this->name ,
					'label'     => $this->model->getAttributeLabel(
						$this->attribute
					) ,
					'model'     => $this->model ,
					'attribute' => $this->attribute ,
					'value'     => $this->value ,

				]
			);
		}
	}
