<?php

namespace system\modules\filemanager\widget;

use system\lib\ActiveRecord;
use system\modules\filemanager\assets\FileSelectorAsset;
use system\modules\gallery\models\GalleryMedias;
use yii\base\Widget;
use yii\widgets\InputWidget;

/**
 * Created by tokapps TM.
 * Programmer: gholamreza beheshtian
 * Mobile:09353466620
 * Company Phone:05138846411
 * Site:http://tokapps.ir
 * Date: 12/30/2018
 * Time: 4:05 AM
 * @property   ActiveRecord $model
 */
class MediaViewWidget extends Widget
{
    public $model;
    public $attribute;
    public $count;
    public $contentType = ['image', 'video'];

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
//			FileSelectorAsset::register( $this->view );
        if (!empty($this->count)) {

            $medias = GalleryMedias::find()->where(['table_id' => $this->model->id, 'table' => $this->model::tableName(), 'type' => $this->contentType, 'language' => \Yii::$app->Language->contentLanguageID(), 'fieldName' => $this->attribute])->limit($this->count)->all();
        } else {

            $medias = GalleryMedias::find()->where(['table_id' => $this->model->id, 'table' => $this->model::tableName(), 'type' => $this->contentType, 'language' => \Yii::$app->Language->contentLanguageID(), 'fieldName' => $this->attribute])->all();
        }

        if (!empty($medias)) {
            echo $this->render(
                '@system/modules/gallery/widgets/views/widgetImageVideoView.php',
                [
                    'model' => $medias,
                    'attribute' => $this->attribute,
                    'id' => $this->attribute,
                    'count' => $this->count
                ]
            );
        }


    }
}
