<?php
	
	namespace system\modules\filemanager\assets;
	
	use system\lib\View;
	use yii\web\AssetBundle;
	
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: 12/29/2018
	 * Time: 2:43 PM
	 */
	class FileSelectorAsset extends AssetBundle {
		
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			$this->sourcePath = realpath( __DIR__ . '/files/widgets' );
		}
		
	
		
		
		public $jsOptions = [ 'position' => View::POS_HEAD ];
		
		public $depends =
			[
				'yii\web\YiiAsset' ,
				'yii\bootstrap\BootstrapAsset' ,
			];
		
	}
