<?php
	
	namespace system\modules\filemanager\assets;
	
	use system\assets\angular\AngularJsAssets;
	use system\lib\View;
	use yii\bootstrap\BootstrapAsset;
	use yii\web\AssetBundle;
	use yii\web\YiiAsset;
	
	/**
	 * Created by tokapps TM.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Company Phone:05138846411
	 * Site:http://tokapps.ir
	 * Date: 12/29/2018
	 * Time: 2:43 PM
	 */
	class LightBoxAssets extends AssetBundle {
		
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			$this->sourcePath = realpath( __DIR__ . '/files/lightbox' );
		}
		
		public $js =
			[
				'js/picturefill.js' ,
				'js/lightgallery.js' ,
				'js/lg-papaer.js',
				'js/lg-autoplay.js',
				'js/lg-fullscreen.js',
				'js/jg-zoom.js',
				'js/lg-hash.js',
				'js/lg-share.js',
			
			];
		public $css =
			[
				'css/lightgallery.css'
			];
		

		
		public $depends =
			[
				'yii\web\YiiAsset' ,
				'yii\bootstrap\BootstrapAsset' ,
			];
		
	}
